### ISSUE TITLE
Inference taking forever for a 3000x4000 aerial image

### ISSUE THREAD

**Issue by koutilya-pnvr** [ultralytics/xview-yolov3#11]
I am trying to test this repo on an aerial image with 3000x4000 resolution. It seems to me that the detect.py is taking forever to output the corresponding output image. I am using the following command:
python detect.py -image_folder data/samples/ -output_folder output_myimg/ -img_size 4000 -conf_thres=0.6

Python 3.7 
pytorch 1.0.1
cudatoolkit 8.0

Any idea whats going wrong?

**Comment by koutilya40192** [comment]
It actually exited with an error:

0 (3, 3000, 4000) row 0/1: 0 Traceback (most recent call last):
  File "detect.py", line 273, in <module>
    detect(opt)
  File "detect.py", line 119, in detect
    pred = model(chip)
  File "/fs/vulcan-scratch/koutilya/scratch0/koutilya/installs/anaconda2/envs/torch_0.4_py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/fs/vulcan-scratch/koutilya/projects/xview-yolov3/models.py", line 236, in forward
    x = module(x)
  File "/fs/vulcan-scratch/koutilya/scratch0/koutilya/installs/anaconda2/envs/torch_0.4_py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/fs/vulcan-scratch/koutilya/scratch0/koutilya/installs/anaconda2/envs/torch_0.4_py3.7/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/fs/vulcan-scratch/koutilya/scratch0/koutilya/installs/anaconda2/envs/torch_0.4_py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/fs/vulcan-scratch/koutilya/projects/xview-yolov3/models.py", line 120, in forward
    p = p.view(bs, self.nA, self.bbox_attrs, nG, nG).permute(0, 1, 3, 4, 2).contiguous()  # prediction
RuntimeError: shape '[1, 10, 65, 32, 32]' is invalid for input of size 2600000

How should I properly test a 3000x4000 aerial image? Any help appreciated!

**Comment by glenn-jocher** [comment]
Be advised that the https://github.com/ultralytics/xview-yolov3 repository is not under active development anymore. We recommend you use https://github.com/ultralytics/yolov3 instead, our main YOLOv3 repository.

**Comment by fadishaar84** [comment]
@koutilya40192 Did you solve the error? I'm facing the same issue.

**Comment by koutilya40192** [comment]
@fadishaar84 no i didn't.

**Comment by DogukanAltay** [comment]
Did you update lines 27 and 51 with "True" and "cuda:0". Probably parsing and doing inference with cpu on such big images takes too much time.
