### ISSUE TITLE
Out memory problem:

### ISSUE THREAD

**Issue by abidmalikwaterloo** [ultralytics/xview-yolov3#3]
I am getting the following problem:

222 layers, 6.26582e+07 parameters, 6.26582e+07 gradients
     Epoch     Batch         x         y         w         h      conf       cls     total         P         R       nGT        TP        FP        FN      time
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    main(opt)
  File "train.py", line 130, in main
    weight=class_weights, epoch=epoch)
  File "/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amalik/OGA/ultralytics/xview-yolov3/models.py", line 221, in forward
    x = module(x)
  File "/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/software/anaconda3/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 447, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/software/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 755, in leaky_relu
    return torch._C._nn.leaky_relu(input, negative_slope)
RuntimeError: CUDA error: out of memory

I reduce the batch size to one but still getting it. What other parameters should I look into to solve this problem?

**Comment by abidmalikwaterloo** [comment]
@glenn-jocher Do you have any feedback on this?  Thanks

**Comment by glenn-jocher** [comment]
Yes, your GPU is out of RAM. You need a smaller batch size, smaller image size, or larger GPU.

**Comment by abidmalikwaterloo** [comment]
@glenn-jocher  Thanks for the reply. I am using a K20 GPU with 6 Gb RAM. I looked at the model summary. The variables + gradients give about 12.6 x 10^6 of parameters. If we are using single precision ( 4 bytes) then the total need of the model is about 48 MB. I am using batch size equal to one. If the size of each data is 0.5 MB then the total memory requirement is about 55 MB. I think 6Gb should work. What is your take on this? I just want to have your feedback before going to another platform.

**Comment by saman-moeinsadat** [comment]
I am having the same issue, after using --multi-scale although I stopped using it getting the same error even with batch-size =1
could i have your feedback on this

**Comment by glenn-jocher** [comment]
@saman-moeinsadat it seems like the issue persists even after adjusting the batch size. Have you tried reducing the image size or using a GPU with more memory?
